# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mcp_pb2 as mcp__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpaceDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCoronalMassEjections = channel.unary_unary(
                '/mcp.SpaceDataService/GetCoronalMassEjections',
                request_serializer=mcp__pb2.CMERequest.SerializeToString,
                response_deserializer=mcp__pb2.CMEResponse.FromString,
                _registered_method=True)
        self.GetNoaaSwpcAlerts = channel.unary_unary(
                '/mcp.SpaceDataService/GetNoaaSwpcAlerts',
                request_serializer=mcp__pb2.AlertsRequest.SerializeToString,
                response_deserializer=mcp__pb2.AlertsResponse.FromString,
                _registered_method=True)


class SpaceDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCoronalMassEjections(self, request, context):
        """Fetch coronal mass ejections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNoaaSwpcAlerts(self, request, context):
        """Fetch NOAA SWPC alerts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpaceDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCoronalMassEjections': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoronalMassEjections,
                    request_deserializer=mcp__pb2.CMERequest.FromString,
                    response_serializer=mcp__pb2.CMEResponse.SerializeToString,
            ),
            'GetNoaaSwpcAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNoaaSwpcAlerts,
                    request_deserializer=mcp__pb2.AlertsRequest.FromString,
                    response_serializer=mcp__pb2.AlertsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.SpaceDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.SpaceDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpaceDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCoronalMassEjections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.SpaceDataService/GetCoronalMassEjections',
            mcp__pb2.CMERequest.SerializeToString,
            mcp__pb2.CMEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNoaaSwpcAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.SpaceDataService/GetNoaaSwpcAlerts',
            mcp__pb2.AlertsRequest.SerializeToString,
            mcp__pb2.AlertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
