# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'mcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcp.proto\x12\x03mcp\"2\n\nCMERequest\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\" \n\x0b\x43MEResponse\x12\x11\n\tdata_json\x18\x01 \x01(\t\"\x0f\n\rAlertsRequest\"#\n\x0e\x41lertsResponse\x12\x11\n\tdata_json\x18\x01 \x01(\t2\x8e\x01\n\x10SpaceDataService\x12<\n\x17GetCoronalMassEjections\x12\x0f.mcp.CMERequest\x1a\x10.mcp.CMEResponse\x12<\n\x11GetNoaaSwpcAlerts\x12\x12.mcp.AlertsRequest\x1a\x13.mcp.AlertsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CMEREQUEST']._serialized_start=18
  _globals['_CMEREQUEST']._serialized_end=68
  _globals['_CMERESPONSE']._serialized_start=70
  _globals['_CMERESPONSE']._serialized_end=102
  _globals['_ALERTSREQUEST']._serialized_start=104
  _globals['_ALERTSREQUEST']._serialized_end=119
  _globals['_ALERTSRESPONSE']._serialized_start=121
  _globals['_ALERTSRESPONSE']._serialized_end=156
  _globals['_SPACEDATASERVICE']._serialized_start=159
  _globals['_SPACEDATASERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
